#!/bin/bash

# Get the name of the current branch in this GIT repo

BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${BUILD_SCRIPTS_DIR}/../git/utils"

git symbolic-ref --short HEAD