#!/bin/bash

# Updates a number of branches that have been created in chain, starting from main

BUILD_SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${BUILD_SCRIPTS_DIR}/../git/utils"

usage_and_exit() {
    echo "Usage: $0 [--safe] [--interactive] [branch-1 branch-2 branch-3 ...]"
    echo "    Updates a number of branches in sequence from main"
    echo "    --safe: (optional) run a full build on each branch after rebasing"
    echo "    --interactive: (optional) do interactive rebase"
    echo "    branch-1: the branch that was created off main"
    echo "    branch-2: a branch created off branch-1"
    echo "    branch-3: a branch created off branch-2"
    echo "    branch-n: a branch created off branch-(n-1)"
    exit 1
}

execute() {
    eval "$* || fail \"Failed to run: $*\""
}

if [[ $# -eq 0 ]]; then
    usage_and_exit
fi

run_build=0
interactive=""
# shellcheck disable=SC2154
execute "git switch ${main} && git pull -r"
previous_branch=${main}

for branch in "$@"; do
    case $branch in
    "--safe")
        run_build=1
        ;;
    "--interactive")
        interactive="-i"
        ;;
    *)
        current_branch=${NEW_BRANCH_PREFIX}${branch}
        execute "git switch ${current_branch} && git rebase $interactive $previous_branch"
        [[ $run_build -eq 1 ]] && execute "run-full-build"
        previous_branch=${current_branch}
        ;;
    esac
done
