#!/bin/sh

# Based largely on https://stackoverflow.com/a/750182/2302613

help() {
	echo "$0 <old-email> <new-email>"
	echo "change committer for the current repository from <old-email> to <new-email>"
}

if [ $# -ne 2 ]; then
	help
	exit 1
fi

git filter-branch -f --env-filter '
OLD_EMAIL="'$1'"
CORRECT_NAME="$(git config user.name)"
CORRECT_EMAIL="'$2'"

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi

if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
'  --tag-name-filter cat -- --branches --tags

