#!/usr/bin/env bash

# Stop tracking one or more files that are currently being tracked

BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${BUILD_SCRIPTS_DIR}/../git/utils"

git rm --cached "$@"

