#!/bin/bash

# Updates the current branch with the latest master value (in remote)

branch_name=$(branch-name)

if [ "${branch_name}" = "master" ]; then
    git pull -r
else
    git checkout master && git pull -r && git checkout ${branch_name} && git rebase master
fi

