#!/usr/bin/env bash

BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

[ -f "$HOME/.bashrc" ] && bashrc="$HOME/.bashrc"
[ -f "$HOME/.bash_profile" ] && bashrc="$HOME/.bash_profile"

echo "# Add bash-utils to path" >>${bashrc}
echo "source ${BUILD_SCRIPTS_DIR}/add-to-path" >>${bashrc}
echo "" >>${bashrc}

