#!/bin/bash

# Login into the Dev space of Cloud Foundry (assuming there is one)

BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd ${BUILD_SCRIPTS_DIR}
source ./cf-common
popd

cf login -a ${CF_HOST} -s dev -u ${CF_USER} -p `cf-password`
