#!/bin/bash

# SSH into a specific application currently running in Cloud Foundry.
# If there are multiple instances running, it will SSH into the first one.
# This script assumes that you are currently logged into Cloud Foundry, if not, check cf-login-*


short_name=$1

if [ -z "${short_name}" ]; then
    echo "You need to specify the application that you want to ssh into:"
    echo "$0 <app_name>"
    exit -1
fi

app_name=`cf-get-app-name ${short_name}`
cf ssh ${app_name}
