#!/usr/bin/env bash

BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${BUILD_SCRIPTS_DIR}/java-commons"


usage_and_exit() {
    echo "Usage: $0 <alias> <cert-file>"
    echo "    <alias> an alias for this certificate (must be unique within the store)"
    echo "    <cert-file> file containing the certificate to store"
    exit 1
}

alias=$1
file=$2

[[ -z "${file}" || -z "${alias}" ]] && usage_and_exit

sudo keytool -importcert -file "${file}" -alias ${alias} ${cacerts_locator}
