#!/usr/bin/env bash

BUILD_SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common/utils
source "${BUILD_SCRIPTS_DIR}/../common/utils"

BREWFILE="$HOME/Brewfile"
# shellcheck disable=SC2088
[ -f "${BREWFILE}" ] || fail "~/Brewfile not found"

log "Updating Brew formulae"
brew update

log "Clean up unneeded packages"
brew bundle --file "${BREWFILE}" cleanup --force

log "Ensure required packages are installed"
brew bundle --file "${BREWFILE}" install

log "Upgrade existing packages to latest"
brew upgrade
